# Generated by Django 5.2.13 on 2026-06-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_drop_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
