# Generated by Django 4.2.28 on 2026-03-13 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_compensation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='month_label',
            field=models.CharField(blank=True, help_text="e.g. 'February 2026'", max_length=20),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='order_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of paid orders in the period'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total sales for the period', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='paymentrecord',
            unique_together={('staff', 'period_start', 'period_end')},
        ),
    ]
