# Generated by Django 4.2.28 on 2026-03-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_compensation', '0002_paymentrecord_month_label_paymentrecord_order_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcompensation',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='eligible_sales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sales from items matching commission scope', max_digits=10),
        ),
        migrations.AddField(
            model_name='staffcompensation',
            name='commission_rate_premium',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission % on premium items (e.g. 15 = 15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='staffcompensation',
            name='commission_rate_regular',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission % on regular items (e.g. 10 = 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='staffcompensation',
            name='commission_scope',
            field=models.CharField(choices=[('regular', 'Regular Items Only'), ('premium', 'Premium Items Only'), ('both', 'Both Regular & Premium')], default='both', help_text='Which item tiers this staff member earns commission on', max_length=10),
        ),
    ]
