# Generated by Django 4.2.28 on 2026-03-15 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_compensation', '0003_remove_staffcompensation_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='disbursement_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa')], help_text='How the payment was disbursed', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='mpesa_transaction_code',
            field=models.CharField(blank=True, help_text='M-Pesa transaction code when paid via M-Pesa', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Bank Details',
                'verbose_name_plural': 'Staff Bank Details',
            },
        ),
    ]
