# Generated by Django 4.2.28 on 2026-03-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_compensation', '0004_paymentrecord_disbursement_method_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentrecord',
            unique_together=set(),
        ),
    ]
