# Generated by Django 4.2.28 on 2026-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_compensation', '0005_alter_paymentrecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Running total of how much has been paid so far', max_digits=10),
        ),
    ]
