# Generated by Django 5.2.13 on 2026-05-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_compensation', '0007_drop_branch_drift'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcompensation',
            name='is_commission_only',
            field=models.BooleanField(default=False, help_text="Non-login staff who exist only for commission attribution. Replaces the legacy 'Attendant' group: login is blocked, but the user is still included in commission queries."),
        ),
    ]
