# Generated by Django 4.2.28 on 2026-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_compensation', '0008_advancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_type',
            field=models.CharField(choices=[('commission', 'Commission'), ('salary', 'Salary'), ('both', 'Salary & Commission')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcompensation',
            name='compensation_type',
            field=models.CharField(choices=[('commission', 'Commission'), ('salary', 'Salary'), ('both', 'Salary & Commission')], max_length=10),
        ),
    ]
