# Generated by Django 5.2.13 on 2026-05-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_compensation', '0009_retire_attendant_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcompensation',
            name='compensation_type',
            field=models.CharField(choices=[('commission', 'Commission'), ('salary', 'Salary')], default='salary', max_length=10),
        ),
    ]
