# Generated by Django 4.2.28 on 2026-03-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_compensation', '0011_restructure_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('disbursed', 'Disbursed')], default='pending', max_length=10),
        ),
    ]
