# Generated by Django 4.2.28 on 2026-03-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitercode',
            name='photo',
            field=models.ImageField(blank=True, upload_to='waiters/'),
        ),
    ]
