# Generated by Django 5.2.13 on 2026-06-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_waitercode_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitercode',
            options={'verbose_name': 'Login Code', 'verbose_name_plural': 'Login Codes'},
        ),
    ]
