# Generated by Django 4.2.28 on 2026-03-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_waitercode_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitercode',
            options={'verbose_name': 'Login Code', 'verbose_name_plural': 'Login Codes'},
        ),
    ]
