# Generated by Django 4.2.28 on 2026-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_waitercode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitercode',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waitercode',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitercode',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
