# Generated by Django 5.2.13 on 2026-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Barista", "Sous Chef"', max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('casual', 'Casual')], default='full_time', max_length=20)),
                ('location', models.CharField(blank=True, help_text='e.g. "Bean & Bite, Kilimani". Leave blank if obvious.', max_length=120)),
                ('summary', models.CharField(blank=True, help_text='One-line teaser shown on the careers page card.', max_length=240)),
                ('description', models.TextField(help_text='What the role is and a sense of the day-to-day.')),
                ('requirements', models.TextField(blank=True, help_text='Skills, experience, or attitude you want. One per line is fine.')),
                ('how_to_apply', models.TextField(help_text='Tell candidates exactly how to apply — e.g. "Email your CV to careers@beanandbite.co.ke" or "Drop your CV at the counter, ask for the manager".')),
                ('is_open', models.BooleanField(default=True, help_text='Untick to hide this opening from the public page without deleting it.')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
