# Generated by Django 4.2.28 on 2026-03-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash Register'), ('mpesa', 'M-Pesa Till'), ('bank', 'Bank Account')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('branch', 'account_type')},
        ),
    ]
