# Generated by Django 4.2.28 on 2026-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_account_branch_transaction_branch_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['branch', 'created_at'], name='administrat_branch__10536f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'transaction_type', 'created_at'], name='administrat_account_665f77_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='administrat_referen_d7ab43_idx'),
        ),
    ]
