# Generated by Django 5.2.13 on 2026-05-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_drop_removed_apps_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash Register'), ('mpesa', 'M-Pesa Till'), ('bank', 'Bank Account'), ('ubereats_ar', 'Uber Eats Receivable'), ('glovo_ar', 'Glovo Receivable'), ('bolt_ar', 'Bolt Food Receivable'), ('jumia_ar', 'Jumia Food Receivable')], max_length=20, unique=True),
        ),
    ]
