# Generated by Django 4.2.28 on 2026-03-16 19:48

from django.db import migrations


DEFAULT_CATEGORIES = [
    ('Rent', 'Monthly rent and lease payments'),
    ('Utilities', 'Electricity, water, gas, internet'),
    ('Food Supplies', 'Ingredients and raw materials not on PO'),
    ('Equipment', 'Kitchen equipment, furniture, repairs'),
    ('Cleaning & Supplies', 'Cleaning products, disposables, packaging'),
    ('Marketing', 'Advertising, promotions, signage'),
    ('Transport', 'Delivery, fuel, vehicle maintenance'),
    ('Licenses & Permits', 'Health permits, liquor licenses, trade licenses'),
    ('Insurance', 'Business, property, liability insurance'),
    ('Maintenance', 'Building repairs, plumbing, electrical'),
    ('Miscellaneous', 'Other business expenses'),
]


def seed_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    for name, desc in DEFAULT_CATEGORIES:
        ExpenseCategory.objects.get_or_create(name=name, defaults={'description': desc})


def remove_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    names = [n for n, _ in DEFAULT_CATEGORIES]
    ExpenseCategory.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
