# Generated by Django 5.2.13 on 2026-06-15 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_advancerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='amount_recovered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How much of this advance has been recovered from wages.', max_digits=10),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='disbursement_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa')], max_length=10),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='mpesa_transaction_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('settled', 'Settled')], default='pending', max_length=10),
        ),
    ]
