# Generated by Django 4.2.28 on 2026-03-19 12:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_transferrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='hr/documents/%Y/%m/', validators=[core.models.validate_file_size, core.models.validate_file_extension]),
        ),
    ]
