# Generated by Django 5.2.13 on 2026-06-09 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0043_restaurantsettings_mpesa_till_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('tea', 'Tea / Break'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('other', 'Other')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit at time of consumption', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_meal_items', to='menu.inventoryitem')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_meal_items', to='menu.menuitem')),
                ('staff_meal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='staff_meals.staffmeallog')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('inventory_item__isnull', True), ('menu_item__isnull', False)), models.Q(('inventory_item__isnull', False), ('menu_item__isnull', True)), _connector='OR'), name='staffmealitem_exactly_one_source')],
            },
        ),
    ]
