# Generated by Django 4.2.28 on 2026-03-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_rename_manager_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text='Location name (e.g. Karen, Lavington). The restaurant name is prepended automatically.', max_length=150),
        ),
    ]
