# Generated by Django 4.2.28 on 2026-03-16 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0015_add_created_by_to_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('spoiled', 'Spoiled / Rotten'), ('overprep', 'Over-preparation'), ('spillage', 'Spillage'), ('returned', 'Customer Return'), ('damaged', 'Damaged'), ('theft', 'Theft / Missing'), ('other', 'Other')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit at time of waste', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_items', to='menu.inventoryitem')),
                ('waste_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='waste.wastelog')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
