# Generated by Django 4.2.28 on 2026-03-15 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtortransaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How much of this invoice has been paid (debit transactions only)', max_digits=10),
        ),
        migrations.CreateModel(
            name='DebtorPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(limit_choices_to={'transaction_type': 'debit'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='debtor.debtortransaction')),
                ('payment', models.ForeignKey(limit_choices_to={'transaction_type': 'credit'}, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='debtor.debtortransaction')),
            ],
            options={
                'unique_together': {('payment', 'invoice')},
            },
        ),
    ]
