# Generated by Django 4.2.28 on 2026-03-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('debtor', '0002_add_invoice_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='branches.branch'),
        ),
    ]
