# Generated by Django 4.2.28 on 2026-03-18 14:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable or disable tax calculation on orders')),
                ('tax_name', models.CharField(default='VAT', help_text='Display name for the tax (e.g. VAT, GST, Sales Tax)', max_length=50)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Tax rate as a percentage (e.g. 16.00 for 16%)', max_digits=5)),
                ('tax_type', models.CharField(choices=[('exclusive', 'Exclusive (added on top of price)'), ('inclusive', 'Inclusive (price already includes tax)')], default='inclusive', help_text='Exclusive: tax added on top. Inclusive: price already includes tax.', max_length=10)),
                ('tax_number', models.CharField(blank=True, help_text='Tax registration / PIN number (shown on receipts)', max_length=50)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configuration',
            },
        ),
    ]
