# Generated by Django 4.2.28 on 2026-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=10),
        ),
    ]
