# Generated by Django 4.2.28 on 2026-03-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_add_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
