# Generated by Django 5.2.13 on 2026-06-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_drop_branch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='received_quantity',
        ),
    ]
