# Generated by Django 5.2.13 on 2026-05-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_drop_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Typical days from placing an order to goods arriving. Drives reorder needed_by dates. Auto-updated from receipt history once ≥5 receipts exist for this supplier.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lead_time_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('learned', 'Learned from receipts')], default='manual', help_text='Whether lead_time_days came from manual entry or was auto-learned from receipt history.', max_length=10),
        ),
    ]
