# Generated by Django 4.2.28 on 2026-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_shift_order_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='starting_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
