# Generated by Django 4.2.28 on 2026-03-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_shift_starting_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
