# Generated by Django 4.2.28 on 2026-03-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order_mpesa_code_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RestoPOS', max_length=150)),
                ('tagline', models.CharField(blank=True, default='Your Favourite Restaurant', max_length=250)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.CharField(blank=True, max_length=150)),
                ('logo', models.ImageField(blank=True, upload_to='restaurant/')),
            ],
            options={
                'verbose_name': 'Restaurant Settings',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
    ]
