# Generated by Django 4.2.28 on 2026-03-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_restaurantsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='Last 4 characters of M-Pesa transaction code', max_length=4),
        ),
    ]
