# Generated by Django 4.2.28 on 2026-03-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_orderitem_unit_price_orderitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='MenuItemVariant',
        ),
    ]
