# Generated by Django 4.2.28 on 2026-03-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_remove_menuitemvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Litres'), ('ml', 'Millilitres'), ('bottle', 'Bottles'), ('piece', 'Pieces'), ('packet', 'Packets'), ('box', 'Boxes'), ('bunch', 'Bunches')], default='piece', max_length=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Link to inventory for direct-sale items (soda, water). Leave blank for prepared food.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menu.inventoryitem'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, help_text='Amount consumed per 1 menu item sold', max_digits=8)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='menu.inventoryitem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='menu.menuitem')),
            ],
            options={
                'verbose_name_plural': 'recipes',
                'unique_together': {('menu_item', 'inventory_item')},
            },
        ),
    ]
