# Generated by Django 4.2.28 on 2026-03-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_add_inventory_and_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_tier',
            field=models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium')], default='regular', help_text='Regular or Premium — affects staff commission eligibility', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit for profit tracking', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Alert when stock falls to this level', max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='For direct-sale items (soda, water). Leave blank for prepared food.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menu.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity_required',
            field=models.DecimalField(decimal_places=3, help_text='Amount of this ingredient consumed per 1 menu item sold', max_digits=8),
        ),
    ]
