# Generated by Django 4.2.28 on 2026-03-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0001_initial'),
        ('menu', '0012_add_preferred_supplier_to_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='debtor.debtor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('credit', 'Credit (Debtor)')], max_length=10),
        ),
    ]
