# Generated by Django 4.2.28 on 2026-03-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_add_debtor_and_credit_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='currency',
            field=models.CharField(default='KES', help_text='Currency code (e.g. KES, USD, EUR)', max_length=3),
        ),
    ]
