# Generated by Django 4.2.28 on 2026-03-17 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_rename_manager_group'),
        ('menu', '0016_inventoryitem_branch_order_branch_shift_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMenuAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_availability', to='branches.branch')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availability', to='menu.menuitem')),
            ],
            options={
                'verbose_name_plural': 'branch menu availability',
                'unique_together': {('branch', 'menu_item')},
            },
        ),
    ]
