# Generated by Django 4.2.28 on 2026-03-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_add_branch_menu_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount calculated at time of order', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax rate applied at time of order', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_type',
            field=models.CharField(blank=True, help_text='inclusive or exclusive at time of order', max_length=10),
        ),
    ]
