# Generated by Django 5.2.13 on 2026-05-01 17:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_add_orderitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='default_markup_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Default markup applied to cost when suggesting menu prices', max_digits=5),
        ),
    ]
