# Generated by Django 4.2.28 on 2026-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_order_tax_amount_order_tax_rate_order_tax_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['branch', 'name'], name='menu_invent_branch__4a73db_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status', 'created_at'], name='menu_order_branch__1e0c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'created_at'], name='menu_order_branch__e97494_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['waiter', 'status'], name='menu_order_waiter__30dd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='menu_order_status_7436bc_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['waiter', 'is_active', 'branch'], name='menu_shift_waiter__38c021_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['branch', 'is_active'], name='menu_shift_branch__f86b44_idx'),
        ),
    ]
