# Generated by Django 4.2.28 on 2026-03-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_inventoryitem_menu_invent_branch__4a73db_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, help_text='Daily sequential order number, e.g. ORD-20260319-001', max_length=20),
        ),
    ]
