# Generated by Django 5.2.13 on 2026-05-01 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_drop_station_orphans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authorization_reason',
            field=models.TextField(blank=True, help_text='Reason given when the order was voided, discounted, or comped'),
        ),
        migrations.AddField(
            model_name='order',
            name='authorized_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved a void/discount/comp on this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manager-authorised discount on this order, in base currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='is_comp',
            field=models.BooleanField(default=False, help_text='Order was comped (free) — counted as a loss-prevention event, not revenue'),
        ),
        migrations.AddField(
            model_name='shift',
            name='counted_cash',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash actually counted in the drawer at shift close', max_digits=10, null=True),
        ),
    ]
