# Generated by Django 5.2.13 on 2026-05-01 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_add_loss_prevention_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_delta', models.DecimalField(decimal_places=2, help_text='Positive = added, negative = removed', max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('source', models.CharField(choices=[('count', 'Physical count'), ('manual', 'Manual adjustment'), ('write_off', 'Write-off')], default='count', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='menu.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
