# Generated by Django 5.2.13 on 2026-05-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_add_stock_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Show this item in the 'Signature brews' section on the public landing page (up to 3 are shown)."),
        ),
    ]
