# Generated by Django 4.2.28 on 2026-03-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_add_station_prep_status_and_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ready_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
