# Generated by Django 5.2.13 on 2026-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_menuitem_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsettings',
            name='name',
            field=models.CharField(default='Bean & Bite', max_length=150),
        ),
    ]
