# Generated by Django 4.2.28 on 2026-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_add_ready_acknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='preparation_status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready')], default='preparing', max_length=10),
        ),
    ]
