# Generated by Django 5.2.13 on 2026-05-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_alter_restaurantsettings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='address',
            field=models.TextField(blank=True, help_text='Street address. Use line breaks for multi-line.'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='directions_url',
            field=models.URLField(blank=True, help_text='Optional "Get directions" link (full Google Maps URL).', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Public contact email shown on the Contact page and footer.', max_length=254),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Optional Google Maps embed URL. In Google Maps → Share → Embed a map → copy the src="..." value from the iframe. Shown on the Contact page if set.', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='X / Twitter profile URL.'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Country code, no +, no spaces. e.g. 254712345678 → opens wa.me link.', max_length=30),
        ),
    ]
