# Generated by Django 4.2.28 on 2026-04-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_change_prep_status_default_to_preparing'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['slug'], name='menu_menuit_slug_c22fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='menu_menuit_categor_ed897a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'preparation_status'], name='menu_orderi_order_i_6ff99f_idx'),
        ),
    ]
