# Generated by Django 5.2.13 on 2026-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_restaurantsettings_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
