# Generated by Django 5.2.13 on 2026-05-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_alter_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine-in'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='dine_in', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('pos', 'POS / Walk-in'), ('phone', 'Phone'), ('ubereats', 'Uber Eats'), ('glovo', 'Glovo'), ('bolt', 'Bolt Food'), ('jumia', 'Jumia Food'), ('other', 'Other')], default='pos', help_text='Where the order came from. Used to split walk-in vs marketplace revenue.', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menu.table'),
        ),
    ]
