# Generated by Django 5.2.13 on 2026-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_order_order_type_order_source_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('credit', 'Credit (Debtor)'), ('ubereats', 'Uber Eats'), ('glovo', 'Glovo'), ('bolt', 'Bolt Food'), ('jumia', 'Jumia Food')], max_length=10),
        ),
    ]
