# Generated by Django 5.2.13 on 2026-05-17 19:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='bolt_commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('25'), help_text='Bolt Food commission percentage taken on gross revenue.', max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='glovo_commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('28'), help_text='Glovo commission percentage taken on gross revenue.', max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='jumia_commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), help_text='Jumia Food commission percentage taken on gross revenue.', max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='ubereats_commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('27'), help_text='Uber Eats commission percentage taken on gross revenue.', max_digits=5),
        ),
    ]
