# Generated by Django 5.2.13 on 2026-05-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_restaurantsettings_bolt_commission_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Decimal degrees, e.g. -1.28333. Needed for weather-aware forecasting.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Decimal degrees, e.g. 36.81667. Needed for weather-aware forecasting.', max_digits=8, null=True),
        ),
    ]
