# Generated by Django 5.2.13 on 2026-05-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_restaurantsettings_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voided_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the order was voided by a supervisor/manager', null=True),
        ),
    ]
