# Generated by Django 5.2.13 on 2026-05-18 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_order_voided_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='counted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='counted_by',
            field=models.ForeignKey(blank=True, help_text="Supervisor / manager who recorded the till count (separation of duties — never the shift's own server)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_shifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
