# Generated by Django 5.2.13 on 2026-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_shift_counted_at_shift_counted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='pending_close_at',
            field=models.DateTimeField(blank=True, help_text='Set when the server requested clock-out and is waiting for a supervisor to count the till. Cleared once the supervisor records the count and finalizes ended_at.', null=True),
        ),
    ]
