# Generated by Django 5.2.13 on 2026-05-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_shift_pending_close_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='bolt_url',
            field=models.URLField(blank=True, help_text='Public restaurant page on Bolt Food. Leave blank to hide the button.'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='glovo_url',
            field=models.URLField(blank=True, help_text='Public restaurant page on Glovo. Leave blank to hide the button.'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='ubereats_url',
            field=models.URLField(blank=True, help_text='Public restaurant page on Uber Eats. Leave blank to hide the button.'),
        ),
    ]
