# Generated by Django 5.2.13 on 2026-05-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_restaurantsettings_bolt_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Tax / VAT / PIN number printed on customer receipts (e.g. KRA PIN).', max_length=50),
        ),
    ]
