# Generated by Django 5.2.13 on 2026-05-27 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_drop_delivery_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccompanimentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Choose a side"', max_length=120)),
                ('is_required', models.BooleanField(default=True, help_text='If ticked, one option must be chosen before the item is added.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=120)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity_required',
            field=models.DecimalField(decimal_places=3, help_text='Amount of this ingredient consumed per 1 item sold', max_digits=8),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='accompaniment_groups',
            field=models.ManyToManyField(blank=True, help_text="Choice groups offered with this item, e.g. 'Choose a side'.", related_name='menu_items', to='menu.accompanimentgroup'),
        ),
        migrations.CreateModel(
            name='AccompanimentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Plantain"', max_length=120)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, help_text='Added to the base item price. 0 for a free side.', max_digits=7)),
                ('is_available', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.accompanimentgroup')),
                ('inventory_item', models.ForeignKey(blank=True, help_text='For a direct-stock side. Leave blank and add a Recipe for a prepared side.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accompaniment_options', to='menu.inventoryitem')),
            ],
            options={
                'ordering': ['group', 'label'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='accompaniment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='menu.accompanimentoption'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('menu_item__isnull', False)), fields=('menu_item', 'inventory_item'), name='unique_menuitem_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('accompaniment_option__isnull', False)), fields=('accompaniment_option', 'inventory_item'), name='unique_option_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accompaniment_option__isnull', True), ('menu_item__isnull', False)), models.Q(('accompaniment_option__isnull', False), ('menu_item__isnull', True)), _connector='OR'), name='recipe_exactly_one_owner'),
        ),
        migrations.AddField(
            model_name='orderitemoption',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.accompanimentoption'),
        ),
        migrations.AddField(
            model_name='orderitemoption',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.orderitem'),
        ),
    ]
