# Generated by Django 5.2.13 on 2026-05-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0037_seed_demo_accompaniments'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompanimentoption',
            name='inventory_quantity',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Units of the linked inventory item consumed per pick (e.g. 0.02 kg of cheese). Ignored when using a recipe.', max_digits=10),
        ),
    ]
