# Generated by Django 5.2.13 on 2026-05-28 19:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0038_accompanimentoption_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanimentoption',
            name='inventory_quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Units of the linked inventory item consumed per pick (e.g. 0.02 kg of cheese). Matches the inventory column precision (2dp). Ignored when using a recipe.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='accompanimentoption',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Added to the base item price. 0 for a free side.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitemoption',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
