# Generated by Django 5.2.13 on 2026-05-29 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0039_alter_accompanimentoption_inventory_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='reopened_at',
            field=models.DateTimeField(blank=True, help_text="Set when a manager reopens this closed shift for correction. While set (and is_active=True) the shift is in correction mode: the waiter's entries are dated to the shift's own date. Cleared when the shift is re-closed.", null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='reopened_by',
            field=models.ForeignKey(blank=True, help_text='Manager who reopened the shift for correction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_shifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
