# Generated by Django 5.2.13 on 2026-05-29 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0004_debtor_created_by'),
        ('menu', '0040_shift_reopened_at_shift_reopened_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offline_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Client-generated id for an order queued offline. Used to deduplicate sync replays so a dropped response can't create the same order twice. Empty for orders placed online.", max_length=64),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('offline_id', ''), _negated=True), fields=('offline_id',), name='unique_offline_id'),
        ),
    ]
