# Generated by Django 5.2.13 on 2026-06-06 20:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0041_order_offline_id_order_unique_offline_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('credit', 'Credit (Debtor)'), ('ubereats', 'Uber Eats'), ('glovo', 'Glovo'), ('bolt', 'Bolt Food'), ('jumia', 'Jumia Food'), ('split', 'Split (multiple modes)')], max_length=10),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('credit', 'Credit (Debtor)'), ('ubereats', 'Uber Eats'), ('glovo', 'Glovo'), ('bolt', 'Bolt Food'), ('jumia', 'Jumia Food'), ('split', 'Split (multiple modes)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mpesa_code', models.CharField(blank=True, help_text='Last 4 characters of the M-Pesa code, for an M-Pesa line', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='menu.order')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
