# Generated by Django 5.2.13 on 2026-06-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0042_alter_order_payment_method_orderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='mpesa_till_number',
            field=models.CharField(blank=True, help_text='M-Pesa Till / Buy Goods number printed on customer receipts.', max_length=20),
        ),
    ]
