# Generated by Django 5.2.13 on 2026-06-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0043_restaurantsettings_mpesa_till_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='receipt_edit_window_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='How many hours after a goods receipt is recorded that it can still be corrected (cleanly undone and re-received) by the person who received it or a manager. After this window only a manager can reverse it.'),
        ),
    ]
