# Generated by Django 5.2.13 on 2026-06-17 22:13

from django.conf import settings
from django.db import migrations, models


def close_duplicate_active_shifts(apps, schema_editor):
    """Resolve any pre-existing duplicate active shifts before the unique
    constraint is added: keep each waiter's most recent active shift and close
    the older stale ones (they were never clocked out). Required so the
    constraint can be applied on data that predates it.
    """
    Shift = apps.get_model('menu', 'Shift')
    from django.db.models import Count

    dup_waiters = (
        Shift.objects.filter(is_active=True)
        .values('waiter')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
        .values_list('waiter', flat=True)
    )
    for waiter_id in list(dup_waiters):
        active = list(
            Shift.objects.filter(waiter_id=waiter_id, is_active=True)
            .order_by('-started_at', '-id')
        )
        # Keep active[0] (most recent); close the rest.
        for stale in active[1:]:
            stale.is_active = False
            if stale.ended_at is None:
                # Close it on its own start day so the z-report stays on the
                # right business day rather than today.
                stale.ended_at = stale.started_at
            stale.save(update_fields=['is_active', 'ended_at'])


def noop(apps, schema_editor):
    # Irreversible: we can't know which shifts were active before dedup.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0044_restaurantsettings_receipt_edit_window_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(close_duplicate_active_shifts, noop),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('waiter',), name='one_active_shift_per_waiter'),
        ),
    ]
