# Generated by Django 4.2.28 on 2026-03-20 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0024_change_prep_status_default_to_preparing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0004_alter_branch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('stocktake', 'Stocktake'), ('damage', 'Damaged Goods'), ('expired', 'Expired'), ('correction', 'Correction'), ('other', 'Other')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stocks.stockadjustment')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale (Order)'), ('cancel', 'Order Cancelled'), ('received', 'Goods Received'), ('adjustment', 'Stock Adjustment'), ('waste', 'Waste')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive = stock in, Negative = stock out', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Stock level after this movement', max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Order number, PO number, adjustment reason, etc.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='menu.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory_item', '-created_at'], name='stocks_stoc_invento_7af6e8_idx'), models.Index(fields=['branch', 'movement_type', '-created_at'], name='stocks_stoc_branch__360ea0_idx')],
            },
        ),
    ]
