"""
Complete list of world currencies with symbols.
Used by RestaurantSettings.currency field.
"""

CURRENCY_CHOICES = [
    ('AED', 'AED — د.إ — UAE Dirham'),
    ('AFN', 'AFN — ؋ — Afghan Afghani'),
    ('ALL', 'ALL — L — Albanian Lek'),
    ('AMD', 'AMD — ֏ — Armenian Dram'),
    ('ANG', 'ANG — ƒ — Netherlands Antillean Guilder'),
    ('AOA', 'AOA — Kz — Angolan Kwanza'),
    ('ARS', 'ARS — $ — Argentine Peso'),
    ('AUD', 'AUD — A$ — Australian Dollar'),
    ('AWG', 'AWG — ƒ — Aruban Florin'),
    ('AZN', 'AZN — ₼ — Azerbaijani Manat'),
    ('BAM', 'BAM — KM — Bosnia-Herzegovina Mark'),
    ('BBD', 'BBD — Bds$ — Barbadian Dollar'),
    ('BDT', 'BDT — ৳ — Bangladeshi Taka'),
    ('BGN', 'BGN — лв — Bulgarian Lev'),
    ('BHD', 'BHD — .د.ب — Bahraini Dinar'),
    ('BIF', 'BIF — FBu — Burundian Franc'),
    ('BMD', 'BMD — $ — Bermudian Dollar'),
    ('BND', 'BND — B$ — Brunei Dollar'),
    ('BOB', 'BOB — Bs. — Bolivian Boliviano'),
    ('BRL', 'BRL — R$ — Brazilian Real'),
    ('BSD', 'BSD — B$ — Bahamian Dollar'),
    ('BTN', 'BTN — Nu. — Bhutanese Ngultrum'),
    ('BWP', 'BWP — P — Botswanan Pula'),
    ('BYN', 'BYN — Br — Belarusian Ruble'),
    ('BZD', 'BZD — BZ$ — Belize Dollar'),
    ('CAD', 'CAD — C$ — Canadian Dollar'),
    ('CDF', 'CDF — FC — Congolese Franc'),
    ('CHF', 'CHF — CHF — Swiss Franc'),
    ('CLP', 'CLP — $ — Chilean Peso'),
    ('CNY', 'CNY — ¥ — Chinese Yuan'),
    ('COP', 'COP — $ — Colombian Peso'),
    ('CRC', 'CRC — ₡ — Costa Rican Colón'),
    ('CUP', 'CUP — $ — Cuban Peso'),
    ('CVE', 'CVE — $ — Cape Verdean Escudo'),
    ('CZK', 'CZK — Kč — Czech Koruna'),
    ('DJF', 'DJF — Fdj — Djiboutian Franc'),
    ('DKK', 'DKK — kr — Danish Krone'),
    ('DOP', 'DOP — RD$ — Dominican Peso'),
    ('DZD', 'DZD — د.ج — Algerian Dinar'),
    ('EGP', 'EGP — E£ — Egyptian Pound'),
    ('ERN', 'ERN — Nfk — Eritrean Nakfa'),
    ('ETB', 'ETB — Br — Ethiopian Birr'),
    ('EUR', 'EUR — € — Euro'),
    ('FJD', 'FJD — FJ$ — Fijian Dollar'),
    ('FKP', 'FKP — £ — Falkland Islands Pound'),
    ('GBP', 'GBP — £ — British Pound'),
    ('GEL', 'GEL — ₾ — Georgian Lari'),
    ('GHS', 'GHS — GH₵ — Ghanaian Cedi'),
    ('GIP', 'GIP — £ — Gibraltar Pound'),
    ('GMD', 'GMD — D — Gambian Dalasi'),
    ('GNF', 'GNF — FG — Guinean Franc'),
    ('GTQ', 'GTQ — Q — Guatemalan Quetzal'),
    ('GYD', 'GYD — G$ — Guyanese Dollar'),
    ('HKD', 'HKD — HK$ — Hong Kong Dollar'),
    ('HNL', 'HNL — L — Honduran Lempira'),
    ('HRK', 'HRK — kn — Croatian Kuna'),
    ('HTG', 'HTG — G — Haitian Gourde'),
    ('HUF', 'HUF — Ft — Hungarian Forint'),
    ('IDR', 'IDR — Rp — Indonesian Rupiah'),
    ('ILS', 'ILS — ₪ — Israeli New Shekel'),
    ('INR', 'INR — ₹ — Indian Rupee'),
    ('IQD', 'IQD — ع.د — Iraqi Dinar'),
    ('IRR', 'IRR — ﷼ — Iranian Rial'),
    ('ISK', 'ISK — kr — Icelandic Króna'),
    ('JMD', 'JMD — J$ — Jamaican Dollar'),
    ('JOD', 'JOD — د.ا — Jordanian Dinar'),
    ('JPY', 'JPY — ¥ — Japanese Yen'),
    ('KES', 'KES — Ksh — Kenyan Shilling'),
    ('KGS', 'KGS — сом — Kyrgystani Som'),
    ('KHR', 'KHR — ៛ — Cambodian Riel'),
    ('KMF', 'KMF — CF — Comorian Franc'),
    ('KPW', 'KPW — ₩ — North Korean Won'),
    ('KRW', 'KRW — ₩ — South Korean Won'),
    ('KWD', 'KWD — د.ك — Kuwaiti Dinar'),
    ('KYD', 'KYD — CI$ — Cayman Islands Dollar'),
    ('KZT', 'KZT — ₸ — Kazakhstani Tenge'),
    ('LAK', 'LAK — ₭ — Lao Kip'),
    ('LBP', 'LBP — ل.ل — Lebanese Pound'),
    ('LKR', 'LKR — Rs — Sri Lankan Rupee'),
    ('LRD', 'LRD — L$ — Liberian Dollar'),
    ('LSL', 'LSL — M — Lesotho Loti'),
    ('LYD', 'LYD — ل.د — Libyan Dinar'),
    ('MAD', 'MAD — د.م. — Moroccan Dirham'),
    ('MDL', 'MDL — L — Moldovan Leu'),
    ('MGA', 'MGA — Ar — Malagasy Ariary'),
    ('MKD', 'MKD — ден — Macedonian Denar'),
    ('MMK', 'MMK — K — Myanmar Kyat'),
    ('MNT', 'MNT — ₮ — Mongolian Tugrik'),
    ('MOP', 'MOP — MOP$ — Macanese Pataca'),
    ('MRU', 'MRU — UM — Mauritanian Ouguiya'),
    ('MUR', 'MUR — Rs — Mauritian Rupee'),
    ('MVR', 'MVR — Rf — Maldivian Rufiyaa'),
    ('MWK', 'MWK — MK — Malawian Kwacha'),
    ('MXN', 'MXN — $ — Mexican Peso'),
    ('MYR', 'MYR — RM — Malaysian Ringgit'),
    ('MZN', 'MZN — MT — Mozambican Metical'),
    ('NAD', 'NAD — N$ — Namibian Dollar'),
    ('NGN', 'NGN — ₦ — Nigerian Naira'),
    ('NIO', 'NIO — C$ — Nicaraguan Córdoba'),
    ('NOK', 'NOK — kr — Norwegian Krone'),
    ('NPR', 'NPR — Rs — Nepalese Rupee'),
    ('NZD', 'NZD — NZ$ — New Zealand Dollar'),
    ('OMR', 'OMR — ر.ع. — Omani Rial'),
    ('PAB', 'PAB — B/. — Panamanian Balboa'),
    ('PEN', 'PEN — S/. — Peruvian Sol'),
    ('PGK', 'PGK — K — Papua New Guinean Kina'),
    ('PHP', 'PHP — ₱ — Philippine Peso'),
    ('PKR', 'PKR — Rs — Pakistani Rupee'),
    ('PLN', 'PLN — zł — Polish Złoty'),
    ('PYG', 'PYG — ₲ — Paraguayan Guarani'),
    ('QAR', 'QAR — ر.ق — Qatari Riyal'),
    ('RON', 'RON — lei — Romanian Leu'),
    ('RSD', 'RSD — din. — Serbian Dinar'),
    ('RUB', 'RUB — ₽ — Russian Ruble'),
    ('RWF', 'RWF — RF — Rwandan Franc'),
    ('SAR', 'SAR — ر.س — Saudi Riyal'),
    ('SBD', 'SBD — SI$ — Solomon Islands Dollar'),
    ('SCR', 'SCR — Rs — Seychellois Rupee'),
    ('SDG', 'SDG — ج.س. — Sudanese Pound'),
    ('SEK', 'SEK — kr — Swedish Krona'),
    ('SGD', 'SGD — S$ — Singapore Dollar'),
    ('SHP', 'SHP — £ — Saint Helena Pound'),
    ('SLE', 'SLE — Le — Sierra Leonean Leone'),
    ('SOS', 'SOS — Sh — Somali Shilling'),
    ('SRD', 'SRD — $ — Surinamese Dollar'),
    ('SSP', 'SSP — £ — South Sudanese Pound'),
    ('STN', 'STN — Db — São Tomé and Príncipe Dobra'),
    ('SYP', 'SYP — £S — Syrian Pound'),
    ('SZL', 'SZL — E — Swazi Lilangeni'),
    ('THB', 'THB — ฿ — Thai Baht'),
    ('TJS', 'TJS — SM — Tajikistani Somoni'),
    ('TMT', 'TMT — T — Turkmenistani Manat'),
    ('TND', 'TND — د.ت — Tunisian Dinar'),
    ('TOP', 'TOP — T$ — Tongan Paʻanga'),
    ('TRY', 'TRY — ₺ — Turkish Lira'),
    ('TTD', 'TTD — TT$ — Trinidad and Tobago Dollar'),
    ('TWD', 'TWD — NT$ — New Taiwan Dollar'),
    ('TZS', 'TZS — TSh — Tanzanian Shilling'),
    ('UAH', 'UAH — ₴ — Ukrainian Hryvnia'),
    ('UGX', 'UGX — USh — Ugandan Shilling'),
    ('USD', 'USD — $ — US Dollar'),
    ('UYU', 'UYU — $U — Uruguayan Peso'),
    ('UZS', 'UZS — сўм — Uzbekistani Som'),
    ('VES', 'VES — Bs.S — Venezuelan Bolívar'),
    ('VND', 'VND — ₫ — Vietnamese Đồng'),
    ('VUV', 'VUV — VT — Vanuatu Vatu'),
    ('WST', 'WST — WS$ — Samoan Tala'),
    ('XAF', 'XAF — FCFA — Central African CFA Franc'),
    ('XCD', 'XCD — EC$ — East Caribbean Dollar'),
    ('XOF', 'XOF — CFA — West African CFA Franc'),
    ('XPF', 'XPF — ₣ — CFP Franc'),
    ('YER', 'YER — ﷼ — Yemeni Rial'),
    ('ZAR', 'ZAR — R — South African Rand'),
    ('ZMW', 'ZMW — ZK — Zambian Kwacha'),
    ('ZWL', 'ZWL — Z$ — Zimbabwean Dollar'),
]

# Lookup: code → symbol
CURRENCY_SYMBOLS = {
    'AED': 'د.إ', 'AFN': '؋', 'ALL': 'L', 'AMD': '֏', 'ANG': 'ƒ',
    'AOA': 'Kz', 'ARS': '$', 'AUD': 'A$', 'AWG': 'ƒ', 'AZN': '₼',
    'BAM': 'KM', 'BBD': 'Bds$', 'BDT': '৳', 'BGN': 'лв', 'BHD': '.د.ب',
    'BIF': 'FBu', 'BMD': '$', 'BND': 'B$', 'BOB': 'Bs.', 'BRL': 'R$',
    'BSD': 'B$', 'BTN': 'Nu.', 'BWP': 'P', 'BYN': 'Br', 'BZD': 'BZ$',
    'CAD': 'C$', 'CDF': 'FC', 'CHF': 'CHF', 'CLP': '$', 'CNY': '¥',
    'COP': '$', 'CRC': '₡', 'CUP': '$', 'CVE': '$', 'CZK': 'Kč',
    'DJF': 'Fdj', 'DKK': 'kr', 'DOP': 'RD$', 'DZD': 'د.ج', 'EGP': 'E£',
    'ERN': 'Nfk', 'ETB': 'Br', 'EUR': '€', 'FJD': 'FJ$', 'FKP': '£',
    'GBP': '£', 'GEL': '₾', 'GHS': 'GH₵', 'GIP': '£', 'GMD': 'D',
    'GNF': 'FG', 'GTQ': 'Q', 'GYD': 'G$', 'HKD': 'HK$', 'HNL': 'L',
    'HRK': 'kn', 'HTG': 'G', 'HUF': 'Ft', 'IDR': 'Rp', 'ILS': '₪',
    'INR': '₹', 'IQD': 'ع.د', 'IRR': '﷼', 'ISK': 'kr', 'JMD': 'J$',
    'JOD': 'د.ا', 'JPY': '¥', 'KES': 'Ksh', 'KGS': 'сом', 'KHR': '៛',
    'KMF': 'CF', 'KPW': '₩', 'KRW': '₩', 'KWD': 'د.ك', 'KYD': 'CI$',
    'KZT': '₸', 'LAK': '₭', 'LBP': 'ل.ل', 'LKR': 'Rs', 'LRD': 'L$',
    'LSL': 'M', 'LYD': 'ل.د', 'MAD': 'د.م.', 'MDL': 'L', 'MGA': 'Ar',
    'MKD': 'ден', 'MMK': 'K', 'MNT': '₮', 'MOP': 'MOP$', 'MRU': 'UM',
    'MUR': 'Rs', 'MVR': 'Rf', 'MWK': 'MK', 'MXN': '$', 'MYR': 'RM',
    'MZN': 'MT', 'NAD': 'N$', 'NGN': '₦', 'NIO': 'C$', 'NOK': 'kr',
    'NPR': 'Rs', 'NZD': 'NZ$', 'OMR': 'ر.ع.', 'PAB': 'B/.', 'PEN': 'S/.',
    'PGK': 'K', 'PHP': '₱', 'PKR': 'Rs', 'PLN': 'zł', 'PYG': '₲',
    'QAR': 'ر.ق', 'RON': 'lei', 'RSD': 'din.', 'RUB': '₽', 'RWF': 'RF',
    'SAR': 'ر.س', 'SBD': 'SI$', 'SCR': 'Rs', 'SDG': 'ج.س.', 'SEK': 'kr',
    'SGD': 'S$', 'SHP': '£', 'SLE': 'Le', 'SOS': 'Sh', 'SRD': '$',
    'SSP': '£', 'STN': 'Db', 'SYP': '£S', 'SZL': 'E', 'THB': '฿',
    'TJS': 'SM', 'TMT': 'T', 'TND': 'د.ت', 'TOP': 'T$', 'TRY': '₺',
    'TTD': 'TT$', 'TWD': 'NT$', 'TZS': 'TSh', 'UAH': '₴', 'UGX': 'USh',
    'USD': '$', 'UYU': '$U', 'UZS': 'сўм', 'VES': 'Bs.S', 'VND': '₫',
    'VUV': 'VT', 'WST': 'WS$', 'XAF': 'FCFA', 'XCD': 'EC$', 'XOF': 'CFA',
    'XPF': '₣', 'YER': '﷼', 'ZAR': 'R', 'ZMW': 'ZK', 'ZWL': 'Z$',
}
