# Generated by Django 5.2.13 on 2026-05-17 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0028_restaurantsettings_bolt_commission_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped (no data)')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_used', models.PositiveIntegerField(default=0)),
                ('rows_written', models.PositiveIntegerField(default=0)),
                ('metric_name', models.CharField(blank=True, max_length=30)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['model_name', '-started_at'], name='ml_modelrun_model_n_7b057c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('user', 'Staff member'), ('inventory_item', 'Inventory item')], db_index=True, max_length=20)),
                ('subject_id', models.PositiveIntegerField(db_index=True)),
                ('subject_label', models.CharField(help_text='Cached display name so reports stay readable if subject is deleted', max_length=150)),
                ('metric', models.CharField(choices=[('cash_variance', 'Cash variance per shift'), ('voids_per_shift', 'Voids per shift'), ('comps_per_shift', 'Comps per shift'), ('discount_pct', 'Discount % per shift'), ('stock_variance', 'Stock variance %')], max_length=30)),
                ('observed_value', models.FloatField()),
                ('expected_value', models.FloatField(help_text='Person/item baseline (mean)')),
                ('z_score', models.FloatField(help_text='Standard deviations from baseline')),
                ('direction', models.CharField(choices=[('high', 'High'), ('low', 'Low')], help_text='Whether observation was above or below baseline', max_length=4)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('occurred_on', models.DateField(db_index=True)),
                ('dismissed', models.BooleanField(db_index=True, default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissal_reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('ml', 'ML model'), ('baseline', 'Baseline (insufficient data)')], default='ml', max_length=10)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_anomalies', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_events', to='menu.shift')),
            ],
            options={
                'ordering': ['-occurred_on', '-z_score'],
                'indexes': [models.Index(fields=['dismissed', '-occurred_on'], name='ml_anomalye_dismiss_4dce0c_idx'), models.Index(fields=['subject_type', 'subject_id'], name='ml_anomalye_subject_ec72fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='BasketRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.FloatField(help_text='Fraction of orders containing both')),
                ('confidence', models.FloatField(help_text='P(consequent | antecedent)')),
                ('lift', models.FloatField(help_text='Confidence / P(consequent); > 1 = positive association')),
                ('n_orders', models.PositiveIntegerField(help_text='Orders the rule was trained on')),
                ('refreshed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('ml', 'ML model'), ('baseline', 'Baseline (insufficient data)')], default='ml', max_length=10)),
                ('antecedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_antecedents', to='menu.menuitem')),
                ('consequent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_consequents', to='menu.menuitem')),
            ],
            options={
                'ordering': ['-lift', '-confidence'],
                'indexes': [models.Index(fields=['antecedent', '-lift'], name='ml_basketru_anteced_9b1cb1_idx')],
                'unique_together': {('antecedent', 'consequent')},
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hour', models.PositiveSmallIntegerField(blank=True, help_text='0-23 for hourly forecast; null = whole-day forecast', null=True)),
                ('qty_p50', models.FloatField(help_text='Median forecast (50th percentile)')),
                ('qty_p90', models.FloatField(help_text='Upper-bound forecast (90th percentile)')),
                ('source', models.CharField(choices=[('ml', 'ML model'), ('baseline', 'Baseline (insufficient data)')], default='ml', max_length=10)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='menu.menuitem')),
            ],
            options={
                'ordering': ['date', 'hour', 'menu_item'],
                'indexes': [models.Index(fields=['date', 'menu_item'], name='ml_demandfo_date_97c2a5_idx')],
                'unique_together': {('menu_item', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='MenuClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('star', 'Star'), ('plowhorse', 'Plowhorse'), ('puzzle', 'Puzzle'), ('dog', 'Dog')], db_index=True, max_length=10)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('units_sold', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margin_pct', models.FloatField()),
                ('popularity_pct', models.FloatField(help_text="This item's share of total units sold in window")),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('ml', 'ML model'), ('baseline', 'Baseline (insufficient data)')], default='ml', max_length=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_classes', to='menu.menuitem')),
            ],
            options={
                'ordering': ['-window_end', 'menu_item'],
                'unique_together': {('menu_item', 'window_start', 'window_end')},
            },
        ),
        migrations.CreateModel(
            name='ReorderSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('needed_by', models.DateField(help_text='Order by this date to avoid stockout')),
                ('days_of_cover', models.FloatField(help_text='Days of stock remaining at current run-rate when this was computed')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('ml', 'ML model'), ('baseline', 'Baseline (insufficient data)')], default='ml', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ordered', 'Ordered'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=10)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_suggestions', to='menu.inventoryitem')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['needed_by', 'inventory_item'],
                'indexes': [models.Index(fields=['status', 'needed_by'], name='ml_reorders_status_f88e60_idx')],
            },
        ),
    ]
