# Generated by Django 5.2.13 on 2026-05-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('source', models.CharField(choices=[('actual', 'Actual (historical)'), ('forecast', 'Forecast')], max_length=10)),
                ('temp_max_c', models.FloatField(blank=True, help_text='Daily max temperature in °C', null=True)),
                ('temp_min_c', models.FloatField(blank=True, help_text='Daily min temperature in °C', null=True)),
                ('precipitation_mm', models.FloatField(blank=True, help_text='Total daily precipitation, mm', null=True)),
                ('is_rainy', models.BooleanField(default=False, help_text='Precipitation > 0.5mm OR weather_code is rain/showers')),
                ('weather_code', models.PositiveSmallIntegerField(blank=True, help_text='WMO weather code (0 clear, 51-67 rain, 95-99 thunder, etc.)', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['source', '-date'], name='ml_weathero_source_570e36_idx')],
            },
        ),
    ]
