# Generated by Django 5.2.13 on 2026-05-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_alter_anomalyevent_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyevent',
            name='metric',
            field=models.CharField(choices=[('cash_variance', 'Cash variance per shift'), ('voids_per_shift', 'Voids per shift'), ('comps_per_shift', 'Comps per shift'), ('discount_pct', 'Discount % per shift'), ('stock_variance', 'Stock variance %'), ('supervisor_cash_variance', 'Cash variance (supervisor-attributed)'), ('count_latency_minutes', 'Till count latency (minutes)'), ('combined_loss_risk', 'Joint risk: voids + cash variance'), ('post_hoc_audit_edits', 'Post-hoc audit-log edits')], max_length=30),
        ),
    ]
